<?php
$mapping = Array(
	"account.account" => "/book/3/3_8/chart_of_accounts.html#creating-a-chart-of-accounts",
	"account.account.template" => "/",  // not yet in book
	"account.account.type" => "/book/3/3_8/chart_of_accounts.html#creating-a-chart-of-accounts",
	"account.analytic.account" => "/book/4/4_09_Accounts/4_09_Accounts.html",
	"account.analytic.default" => "/",  // not yet in book
	"account.analytic.journal" => "/book/4/4_09_Accounts/4_09_Accounts_place.html",
	"account.analytic.line" => "/book/4/4_09_Accounts/4_09_Accounts.html",
	"account.analytic.plan" => "/",  // not yet in book
	"account.analytic.plan.instance" => "/",  // not yet in book
	"account.analytic.plan.instance.line" =>"/",  // not yet in book
	"account.analytic.plan.line" =>"/",  // not yet in book
	"account.asset.asset" =>"/",  // not yet in book
	"account.asset.board" => "/",  // not yet in book
	"account.asset.category" =>"/",  // not yet in book
	"account.asset.property" => "/",  // not yet in book
	"account.asset.property.history" =>"/",  // not yet in book
	"account.bank.accounts.wizard" => "/", // not yet in book
	"account.bank.statement" => "/book/3/3_6/accounting_entries.html",
	"account.bank.statement.line" => "/book/3/3_6/accounting_entries.html",
	"account.bank.statement.reconcile" => "/book/3/3_6/accounting_entries.html",
	"account.bank.statement.reconcile.line" => "/book/3/3_6/accounting_entries.html",
	"account.budget.post" => "/book/3/3_7/company_financial_analysis.html#good-management-budgeting"
	"account.budget.post.dotation" => "/",  // not yet in book
	"account.chart.template" => ""/",  // not yet in book",
	"account.config.wizard" => "/",  // not yet in book
	"account.fiscal.position" => "/",// not yet in book
	"account.fiscal.position.account" => "/",// not yet in book
	"account.fiscal.position.account.template" => "/",// not yet in book
	"account.fiscal.position.tax" => "/",// not yet in book
	"account.fiscal.position.tax.template" => "/",// not yet in book
	"account.fiscal.position.template" => "/",// not yet in book
	"account.fiscalyear" => "/book/3/3_8/periods_and_fiscal_years.html",
	"account.invoice" => "/book/3/3_6/invoicing.html",
	"account.invoice.line" => "/book/3/3_6/invoicing.html",
	"account.invoice.tax" => "/book/3/3_6/invoicing.html",
	"account.journal" => "/book/3/3_8/journals.html",
	"account.journal.column" => "/", // not yet in book
	"account.journal.period" => "/", // not yet in book
	"account.journal.simulation" => "/", // not yet in book
	"account.journal.view" => "/", // not yet in book
	"account.model" => "/", // not yet in book
	"account.model.line" => "/", // not yet in book
	"account.move" => "/", // not yet in book
	"account.move.line" => "/", // not yet in book
	"account.move.reconcile" => "/", // not yet in book
	"account.payment.term" => "/book/3/3_8/payment_terms.html",
	"account.payment.term.line" => "/book/3/3_8/payment_terms.html",
	"account.period" => "/book/3/3_8/periods_and_fiscal_years.html",
	"account.report.history" => "/book/4/4_09_Accounts/4_09_Accounts_fin_ana.html",
	"account.report.report" => "/book/4/4_09_Accounts/4_09_Accounts_fin_ana.html",
	"account.sequence.fiscalyear" => "/",// not yet in book
	"account.subscription" => "/",// not yet in book
	"account.subscription.line" => "/",// not yet in book
	"account.tax" => "/book/3/3_7/statutory_taxes.html",
	"account.tax.code" => "/book/3/3_7/statutory_taxes.html",
	"account.tax.code.template" => "book/3/3_7/statutory_taxes.html",
	"account.tax.template" => "/book/3/3_7/statutory_taxes.html",
	"account_analytic_analysis.summary.month" => "/book/4/4_09_Accounts/4_09_Accounts_fin_ana.html",
	"account_analytic_analysis.summary.user" => "/book/4/4_09_Accounts/4_09_Accounts_fin_ana.html",
	"account_followup.followup" => "/book/3/3_7/managing_accounts.html#multi-step-follow-ups",
	"account_followup.followup.line" => "/book/3/3_7/managing_accounts.html#multi-step-follow-ups",
	"account_followup.stat" => "/book/3/3_7/managing_accounts.html#multi-step-follow-ups",
	"board.board" => "/book/3/3_7/company_financial_analysis.html#the-accounting-dashboard"
	"board.board.line" => "/book/3/3_7/company_financial_analysis.html#the-accounting-dashboard"
	"board.note" => "/book/3/3_7/company_financial_analysis.html#the-accounting-dashboard"
	"board.note.type" => "/book/3/3_7/company_financial_analysis.html#the-accounting-dashboard"
	"config.compute.remaining" => "/",// not yet in book
	"crm.case" => "/book/2/2_4_CRM/2_4_CRM_case.html",
	"crm.case.categ" => "/book/2/2_4_CRM/2_4_CRM_case.html#categories",
	"crm.case.category2" => "/book/2/2_4_CRM/2_4_CRM_case.html",
	"crm.case.history" => "/",// not yet in book
	"crm.case.log" => "/",// not yet in book
	"crm.case.rule" => "/book/2/2_4_CRM/2_4_CRM_case.html#automating-actions-using-rules",
	"crm.case.section" => "/",// not yet in book
	"crm.case.stage" => "/",// not yet in book
	"crm.menu.config_wizard" => "/",// not yet in book
	"crm.segmentation" => "/",// not yet in book
	"crm.segmentation.line" =>"/",// not yet in book
	"crossovered.budget" => "/",// not yet in book
	"crossovered.budget.lines" => "/",// not yet in book
	"delivery.carrier" => "/book/6/6_14_Sale_Management/index.html#using-delivery-modes",
	"delivery.grid" => "/book/6/6_14_Sale_Management/index.html#using-delivery-modes",
	"delivery.grid.line" =>"/",// not yet in book
	"document.configuration.wizard" =>"/book/7/7_17_Document_Management/7_17_Document_Management_OpenERP.html#installation",
	"document.directory" => "/book/7/7_17_Document_Management/7_17_Document_Management_mapping.html",
	"document.directory.content" => "/book/7/7_17_Document_Management/7_17_Document_Management_mapping.html",
	"document.directory.content.type" =>"/book/7/7_17_Document_Management/7_17_Document_Management_mapping.html",
	"edi.log" => "/",// not yet in book
	"edi.log.line" =>"/",// not yet in book
	"event.event" =>"/",// not yet in book
	"event.registration" =>"/",// not yet in book
	"event.type" => "/",// not yet in book
	"fiscalyear.seq" =>  "/",// not yet in book
	"hr.action.reason" => "/",// not yet in book
	"hr.analytic.timesheet" => "/book/4/4_10_HR/4_10_HR_timesheet.html",
	"hr.attendance" =>  "book/4/4_10_HR/4_10_HR_timesheet.html#entering-timesheet-data",
	"hr.department" => "/book/4/4_10_HR/4_10_HR_timesheet.html#managing-by-department",
	"hr.employee" =>  "/book/4/4_10_HR/4_10_HR_timesheet.html#employee-configuration"
	"hr.employee.category" =>  "/",// not yet in book
	"hr.expense.expense" => "/book/4/4_11_Services/4_11_Services_treatment.html",
	"hr.expense.line" => "/book/4/4_11_Services/4_11_Services_treatment.html",
	"hr.timesheet" => "/book/4/4_10_HR/4_10_HR_timesheet.html",
	"hr.timesheet.group" => "/book/4/4_10_HR/4_10_HR_timesheet.html",
	"hr_timesheet_invoice.factor" => "/book/4/4_10_HR/4_10_HR_timesheet.html#evaluation-of-service-costs"
	"hr_timesheet_sheet.sheet" => "/book/4/4_10_HR/4_10_HR_timesheet.html#entering-timesheet-data"
	"hr_timesheet_sheet.sheet.account" =>"/book/4/4_10_HR/4_10_HR_timesheet.html#entering-timesheet-data"
	"hr_timesheet_sheet.sheet.day" =>  "/book/4/4_10_HR/4_10_HR_timesheet.html#managing-by-department",
	"ir.actions.act_window" => "/technical_guide/base.html#object-ir-actions-act-window",
	"ir.actions.act_window.view" => "/technical_guide/base.html#object-ir-actions-act-window-view",
	"ir.actions.act_window_close" => "/technical_guide/base.html#object-ir-actions-act-window-close",
	"ir.actions.actions" => "/technical_guide/base.html#object-ir-actions-actions"
	"ir.actions.configuration.wizard" => "/technical_guide/base.html#object-ir-actions-configuration-wizard"
	"ir.actions.report.custom" => "/technical_guide/base.html#object-ir-actions-configuration-wizard"
	"ir.actions.report.xml" =>"/technical_guide/base.html#object-ir-actions-report-xml"
	"ir.actions.server" => "/technical_guide/base.html#object-ir-actions-server"
	"ir.actions.todo" => "/technical_guide/base.html#object-ir-actions-todo"
	"ir.actions.url" => "/technical_guide/base.html#object-ir-actions-url"
	"ir.actions.wizard" => "/technical_guide/base.html#object-ir-actions-wizard"
	"ir.attachment" =>"/technical_guide/base.html#object-ir-attachment"
	"ir.cron" => "/technical_guide/base.html#object-ir-cron"
	"ir.default" => "/technical_guide/base.html#object-ir-default"
	"ir.exports" => "/technical_guide/base.html#object-ir-exports"
	"ir.exports.line" =>"/technical_guide/base.html#object-ir-exports-line"
	"ir.model" => "/",// not yet in book
	"ir.model.access" => "/technical_guide/base.html#object-ir-model-access"
	"ir.model.config" => "/technical_guide/base.html#object-ir-model-config"
	"ir.model.data" => "/technical_guide/base.html#object-ir-model-data"
	"ir.model.fields" => "/",// not yet in book
	"ir.model.grid" =>  "/",// not yet in book
	"ir.module.category" =>"/technical_guide/base.html#object-module-category",
	"ir.module.module" => "/technical_guide/base.html#object-module",
	"ir.module.module.dependency" => "/technical_guide/base.html#object-module-dependency",
	"ir.module.repository" => "/technical_guide/base.html#object-module-repository",
	"ir.property" => "/technical_guide/base.html#object-ir-property",
	"ir.report.custom" => "/technical_guide/base.html#object-ir-report-custom",
	"ir.report.custom.fields" =>"/technical_guide/base.html#object-ir-report-custom-fields",
	"ir.rule" =>"/technical_guide/base.html#object-ir-rule",
	"ir.rule.group" =>"/technical_guide/base.html#object-ir-rule-group",
	"ir.sequence" =>"/technical_guide/base.html#object-ir-sequence",
	"ir.sequence.type" =>"/technical_guide/base.html#object-ir-sequence-type",
	"ir.server.object.lines" => "/technical_guide/base.html#object-ir-server-object-lines",
	"ir.translation" => "/technical_guide/base.html#object-ir-translation",
	"ir.ui.menu" => "/technical_guide/base.html#object-ir-ui-menu",
	"ir.ui.view" =>"/technical_guide/base.html#object-ir-ui-view",
	"ir.ui.view.custom" => "/technical_guide/base.html#object-ir-ui-view-custom",
	"ir.ui.view_sc" => "/technical_guide/base.html#object-ir-ui-view-sc",
	"ir.values" => "/technical_guide/base.html#object-ir-values",
	"maintenance.contract" => "/book/8/8_14_Implem/8_14_Implem_support.html",
	"maintenance.contract.module" => "/technical_guide/base.html#object-maintenance-contract-modules",
	"maintenance.contract.wizard" => "/technical_guide/base.html#object-maintenance-contract-wizard",
	"membership.membership_line" =>  "/features/membership.html"
	"mrp.bom" => "/book/5/5_13_Manufacturing/5_13_Manufacturing_production.html#bills-of-materials",
	"mrp.bom.revision" => "/book/5/5_13_Manufacturing/5_13_Manufacturing_production.html#bills-of-materials",
	"mrp.procurement" => "/book/5/5_13_Manufacturing/5_13_Manufacturing_lead.html#manual-procurement",
	"mrp.production" => "book/5/5_13_Manufacturing/index.html"
	"mrp.production.product.line" => "book/5/5_13_Manufacturing/index.html"
	"mrp.production.workcenter.line" => "/book/5/5_13_Manufacturing/5_13_Manufacturing_lead.html#workcenters"
	"mrp.property" => "/",// not yet in book
	"mrp.property.group" => "/",// not yet in book
	"mrp.repair" => "/book/5/5_13_Manufacturing/5_13_Manufacturing_repairs.html"
	"mrp.repair.fee" => "/book/5/5_13_Manufacturing/5_13_Manufacturing_repairs.html"
	"mrp.repair.line" => "/book/5/5_13_Manufacturing/5_13_Manufacturing_repairs.html"
	"mrp.routing" => "/book/5/5_13_Manufacturing/5_13_Manufacturing_operations.html#routing"
	"mrp.routing.workcenter" => "/book/5/5_13_Manufacturing/5_13_Manufacturing_operations.html#workcenters"
	"mrp.subproduct" => "/book/5/5_13_Manufacturing/5_13_Manufacturing_subcontracting.html",
	"mrp.workcenter" => "/book/5/5_13_Manufacturing/5_13_Manufacturing_operations.html#workcenters",
	"payment.line" => "/book/3/3_6/accounting_entries.html#management-of-payments",
	"payment.mode" => "/book/3/3_6/accounting_entries.html#management-of-payments",
	"payment.order" => "/book/3/3_6/accounting_entries.html#management-of-payments",
	"payment.type" => "/book/3/3_6/accounting_entries.html#management-of-payments",
	"pos.config.journal" => "/features/point_of_sales.html"
	"pos.order" =>"/features/point_of_sales.html",
	"pos.order.line" => "/features/point_of_sales.html"
	"pos.payment" => "/features/point_of_sales.html",
	"pricelist.partnerinfo" => "/",// not yet in book
	"process.condition" => "/book/7/7_16_Process/index.html",
	"process.node" => "/book/7/7_16_Process/index.html",
	"process.process" => "/book/7/7_16_Process/index.html",
	"process.transition" => "/book/7/7_16_Process/index.html",
	"process.transition.action" => "/book/7/7_16_Process/index.html",
	"product.category" =>  "/",// not yet in book
	"product.packaging" =>  "/",// not yet in book
	"product.price.type" =>  "/",// not yet in book
	"product.pricelist" =>  "/book/4/4_11_Services/4_11_Services_price.html#creating-pricelists",
	"product.pricelist.item" => "/book/4/4_11_Services/4_11_Services_price.html#creating-pricelists",
	"product.pricelist.type" => "/book/4/4_11_Services/4_11_Services_price.html#creating-pricelists",
	"product.pricelist.version" =>"/book/4/4_11_Services/4_11_Services_price.html#pricelist-versions",
	"product.product" => "/book/1/1_2_Guided_Tour/1_2_Guided_Tour_openerp.html#products"
	"product.supplierinfo" => "/book/1/1_2_Guided_Tour/1_2_Guided_Tour_openerp.html#products",
	"product.template" => "/book/1/1_2_Guided_Tour/1_2_Guided_Tour_openerp.html#products",
	"product.ul" =>"/book/1/1_2_Guided_Tour/1_2_Guided_Tour_openerp.html#products",
	"product.uom" => "/book/1/1_2_Guided_Tour/1_2_Guided_Tour_openerp.html#products",
	"product.uom.categ" =>"/book/1/1_2_Guided_Tour/1_2_Guided_Tour_openerp.html#products",
	"profile.accounting.config.install_modules_wizard" => "/",// not yet in book
	"profile.association.config.install_modules_wizard" => "/",// not yet in book
	"profile.manufacturing.config.install_modules_wizard" => "/",// not yet in book
	"profile.service.config.install_modules_wizard" => "/",// not yet in book
	"project.gtd.context" => "/",// not yet in book
	"project.gtd.timebox" => "/",// not yet in book
	"project.project" => "/book/4/4_12_Projects/4_12_Projects_management.html"
	"project.task" => "/book/4/4_12_Projects/4_12_Projects_management.html#managing-tasks",
	"project.task.type" => "/book/4/4_12_Projects/4_12_Projects_management.html#managing-tasks",
	"project.task.work" => "/book/4/4_12_Projects/4_12_Projects_management.html#managing-tasks",
	"purchase.order" => "/book/6/6_15_Purchase_Management/index.html",
	"purchase.order.line" => "/book/6/6_15_Purchase_Management/index.html",
	"report.account.analytic.line.to.invoice" => "/",// not yet in book
	"report.account.invoice" =>"/",// not yet in book
	"report.account.invoice.category" =>"/",// not yet in book
	"report.account.invoice.partner" => "/",// not yet in book
	"report.account.invoice.partner.product" => "/",// not yet in book
	"report.account.invoice.product" => "/",// not yet in book
	"report.account.receivable" => "/",// not yet in book
	"report.analytic.account.close" => "/",// not yet in book
	"report.crm.case.categ" => "/",// not yet in book
	"report.crm.case.section.categ.categ2" => "/",// not yet in book
	"report.crm.case.section.categ.stage" => "/",// not yet in book
	"report.crm.case.section.categ2" => "/",// not yet in book
	"report.crm.case.section.stage" => "/",// not yet in book
	"report.crm.case.user" => "/",// not yet in book
	"report.document.file" =>"/",// not yet in book
	"report.document.user" => "/",// not yet in book
	"report.document.wall" => "/",// not yet in book
	"report.event.registration" => "/",// not yet in book
	"report.event.type.registration" => "/",// not yet in book
	"report.files.partner" => "/",// not yet in book
	"report.hr.timesheet.invoice.journal" => "/",// not yet in book
	"report.mrp.inout" => "/",// not yet in book
	"report.partner_member.year" => "/",// not yet in book
	"report.partner_member.year_new" =>"/",// not yet in book
	"report.stock.lines.date" => "/",// not yet in book
	"report.task.user.pipeline.open" => "/",// not yet in book
	"report.transaction.pos" => "/",// not yet in book
	"report.workcenter.load" => "/",// not yet in book
	"report_account_analytic.planning" => "/",// not yet in book
	"report_account_analytic.planning.line" => "/",// not yet in book
	"report_account_analytic.planning.stat" => "/",// not yet in book
	"report_account_analytic.planning.stat.account" => "/",// not yet in book
	"report_account_analytic.planning.stat.user" => "/",// not yet in book
	"report_timesheet.account" => "/",// not yet in book
	"report_timesheet.account.date" => "/",// not yet in book
	"report_timesheet.invoice" => "/",// not yet in book
	"report_timesheet.user" => "/",// not yet in book
	"res.bank" => "/",// not yet in book
	"res.company" => "/",// not yet in book
	"res.config.view" => "/",// not yet in book
	"res.country" => "/",// not yet in book
	"res.country.state" =>"/",// not yet in book
	"res.currency" => "/",// not yet in book
	"res.currency.rate" => "/",// not yet in book
	"res.groups" => "/book/8/8_13_Personalization/8_13_Personalization_accessRights.html#groups-and-users",
	"res.lang" => "/",
	"res.partner" => "/book/2/2_4_CRM/2_4_CRM_partners.html#partners",
	"res.partner.address" => "/book/1/1_3_Real_Case/1_3_Real_Case_db_setup.html#creating-partner-categories-partners-and-their-contacts" // "/technical_guide/base.html#object-partner-addresses"
	"res.partner.bank" => "/technical_guide/base.html#object-bank-accounts",
	"res.partner.bank.type" => "/technical_guide/base.html#object-bank-account-type",
	"res.partner.bank.type.field" => "/technical_guide/base.html#object-bank-type-fields",
	"res.partner.canal" => "/technical_guide/base.html#object-channels",
	"res.partner.category" => "/book/1/1_2_Guided_Tour/1_2_Guided_Tour_connect_openerp.html#partner-categories" // "/book/1/1_3_Real_Case/1_3_Real_Case_db_setup.html#creating-partner-categories-partners-and-their-contacts"
	"res.partner.contact" => "/book/2/2_4_CRM/2_4_CRM_partners.html#contacts",
	"res.partner.event" => "/",
	"res.partner.event.type" => "/",
	"res.partner.function" => "/book/2/2_4_CRM/2_4_CRM_partners.html#contacts", // "/technical_guide/base.html#object-function-of-the-contact"
	"res.partner.job" => "/technical_guide/base_contact.html#object-contact-partner-function",
	"res.partner.som" => "/technical_guide/base.html#object-res-partner-som",
	"res.partner.title" => "/book/2/2_4_CRM/2_4_CRM_partners.html#partners",
	"res.payterm" => "/book/3/3_8/payment_terms.html#payment-terms",
	"res.request" => "/book/1/1_2_Guided_Tour/1_2_Guided_Tour_connect_openerp.html#requests-as-a-mechanism-for-internal-communication",
	"res.request.history" => "/book/1/1_2_Guided_Tour/1_2_Guided_Tour_connect_openerp.html#requests-as-a-mechanism-for-internal-communication",
	"res.request.link" => "/book/1/1_2_Guided_Tour/1_2_Guided_Tour_connect_openerp.html#requests-as-a-mechanism-for-internal-communication",
	"res.roles" => "/book/8/8_13_Personalization/8_13_Personalization_workflow.html#assigning-roles",
	"res.users" => "/book/1/1_2_Guided_Tour/1_2_Guided_Tour_connect_openerp.html#configuring-users",
	"sale.config.picking_policy" => "/book/6/6_14_Sale_Management/index.html#control-of-deliveries-and-invoicing",
	"sale.order" => "/book/6/6_14_Sale_Management/index.html#management-of-sales",
	"sale.order.line" => "/book/6/6_14_Sale_Management/index.html#entering-quotation-details",
	"sale.shop" => "/book/1/1_3_Real_Case/1_3_Real_Case_testing_wf.html#from-sales-proposal-to-sales-order",
	"sale_journal.invoice.type" => "/",
	"sale_journal.invoice.type.stats" => "/",
	"sale_journal.picking.journal" => "/",
	"sale_journal.picking.stats" => "/",
	"sale_journal.sale.journal" => "/",
	"sale_journal.sale.stats" => "/",
	"stock.incoterms" => "/",
	"stock.inventory" => "/book/5/5_12_Stock_Management/5_12_stock_management_stocks.html#initial-inventory",
	"stock.inventory.line" => "/book/5/5_12_Stock_Management/5_12_stock_management_stocks.html#initial-inventory",
	"stock.location" => "/book/5/5_12_Stock_Management/index.html#logistics-and-stock-management",
	"stock.location.path" => "/",
	"stock.move" => "/book/5/5_12_Stock_Management/5_12_stock_management_lots.html#stock-moves",
	"stock.picking" => "/",
	"stock.picking.move.wizard" => "/book/5/5_12_Stock_Management/5_12_stock_management_advanced.html#manual-data-entry-of-goods-receipt",
	"stock.production.lot" => "book/5/5_13_Manufacturing/5_13_Manufacturing_wf.html#traceability",
	"stock.production.lot.revision" => "book/5/5_13_Manufacturing/5_13_Manufacturing_wf.html#traceability",
	"stock.report.prodlots" => "/book/5/5_12_Stock_Management/5_12_stock_management_lots.html#traceability",
	"stock.tracking" => "/book/5/5_12_Stock_Management/5_12_stock_management_lots.html#traceability",
	"stock.warehouse" => "/book/5/5_12_Stock_Management/5_12_stock_management_warehouses.html#warehouses",
	"stock.warehouse.orderpoint" => "/book/5/5_12_Stock_Management/5_12_stock_management_warehouses.html#minimum-stock-rules",
	"wiki.groups" => "/",// not yet in book
	"wiki.groups.link" => "/",// not yet in book
	"wiki.wiki" => "/",// not yet in book
	"wiki.wiki.history" => "/",// not yet in book
	"wizard.ir.model.menu.create" => "/",
	"wizard.ir.model.menu.create.line" => "/",
	"wizard.module.lang.export" => "/book/8/8_13_Personalization/8_13_Personalization_menu.html#translation-through-a-csv-file",
	"wizard.module.update_translations" => "/book/1/1_2_Guided_Tour/1_2_Guided_Tour_connect_openerp.html#installing-a-new-language",
	"wizard.multi.charts.accounts" => "/book/3/3_8/chart_of_accounts.html#creating-a-chart-of-accounts",
	"wizard.wiki.history.show_diff" => "/",
	"workflow" => "/book/8/8_13_Personalization/8_13_Personalization_workflow.html",
	"workflow.activity" => "/developer/5_Workflow/index.html#activity",
	"workflow.instance" => "/",
	"workflow.transition" => "/developer/5_Workflow/index.html#transition",
	"workflow.triggers" => "/developer/5_Workflow/index.html#trigger",
	"workflow.workitem" => "/developer/5_Workflow/index.html#id1",
);
if (has_key($mapping, $_GET['model'])
	header('Location: /'.$mapping[$_GET['model']] ) ;
else
	header('Location: /index.html') ;
?>
